config/routes.rb
Rails.application.routes.draw do

  resources :matriculas, except: :show
  resources :cursos, except: :show
  resources :alunos, except: :show

  post 'matriculas/pagamento/:id(.:format)', to: 'pagamento_matricula#edit', as: 'matriculas/pagamento'
  put 'matriculas/cancellation/:id(.:format)', to: 'matriculas#cancellation', as: 'matriculas/cancellation'
  get 'home/index'
  root 'home#index'

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  before_destroy :aluno_matriculado?
  has_many :matriculas

  validates_associated :matriculas
  validates_uniqueness_of :cpf
  validates_presence_of :nome, :cpf, :rg
  validates_numericality_of :rg, :cpf, :telefone, { only_integer: true, message: I18n.t('messages.numbers_only'), allow_blank: true }
  validates :cpf, length: { minimum: 11, maximum: 11, message: I18n.t('messages.only_11') }, allow_blank: true
  validates :rg, length: { maximum: 9, message: I18n.t('messages.max_9') }, allow_blank: true
  validates :nome, length: { maximum: 255, message: I18n.t('messages.max_255') }, allow_blank: true
  validates :telefone, length: { minimum: 11, maximum: 11, message: I18n.t('messages.only_11') }, allow_blank: true

  validate do
    if cpf != ""
      errors.add(:cpf, :invalid) unless cpf.valid_cpf?
    end
  end

  private
  def aluno_matriculado?
    if Matricula.where("aluno_id = ?", id).count > 0
      return false
    end

    return true
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all.page(params[:page]).per(15)
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to alunos_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to alunos_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    if @aluno.destroy
      respond_to do |format|
        format.html { redirect_to alunos_path, notice: I18n.t('messages.destroyed') }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to alunos_path, alert: I18n.t('messages.error_destroyed') }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:cpf, :rg, :data_nascimento, :nome, :telefone)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
  def formata_telefone(fone)
    (fone != "") ? "(#{fone[0,2]}) #{fone[2,5]}-#{fone[7,4]}" : ""
  end
end

app/views/alunos/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@aluno, html: { class: "form-horizontal" }) do |f| %>
      <div class="form-group">
        <%= f.label :nome, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :nome, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :cpf, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :cpf, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :rg, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :rg, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :data_nascimento, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.date_select :data_nascimento, start_year: Date.current.year, end_year: 1900, html_options: { class: "form-control" } %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :telefone, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :telefone, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
          <%= f.submit t('buttons.save'), class: "btn btn-default" %>
          <%= link_to t('buttons.back'), alunos_path, class: "btn btn-default"%>
        </div>
      </div>

      <% if @aluno.errors.any? %>
        <div id="error_explanation" class="alert alert-danger col-xs-offset-1 col-xs-10" role="alert">
          <ul>
          <% @aluno.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

    <script type="text/javascript">
      $("#aluno_data_nascimento_1i").change(function() {
        var ano = this.value;
        if ((ano % 4) == 0 && ((ano % 100) != 0 || ((ano % 100) == 0 && (ano % 400) == 0))) {
          showModalInfo('Ano bissexto');
        }
      });

      $(".form-group:has(.field_with_errors)").addClass("has-error");
      $("select").addClass("form-control").css("width", "33.33%").css("float", "left");
    </script>
  </div>
</div>

app/views/alunos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.editing')} #{t('activerecord.models.aluno.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>

app/views/alunos/index.html.erb
<% if notice != nil %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <%= notice %>
  </div>
<% end %>

<% if alert != nil %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
    <%= alert %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.listing')} #{@alunos.model.model_name.human(count: 2)}" %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @alunos.model.human_attribute_name("nome") %></th>
        <th><%= @alunos.model.human_attribute_name("cpf") %></th>
        <th><%= @alunos.model.human_attribute_name("rg") %></th>
        <th><%= @alunos.model.human_attribute_name("data_nascimento") %></th>
        <th><%= @alunos.model.human_attribute_name("telefone") %></th>
        <th><%= t("buttons.actions") %></th>
      </tr>
    </thead>

    <tbody>
      <% @alunos.each do |aluno| %>
        <tr>
          <td><%= aluno.nome %></td>
          <td><%= aluno.cpf.to_cpf_format %></td>
          <td><%= aluno.rg %></td>
          <td><%= aluno.data_nascimento.strftime("%d/%m/%Y") %></td>
          <td><%= formata_telefone(aluno.telefone) %></td>
          <td><%= link_to "", edit_aluno_path(aluno), class: "glyphicon glyphicon-pencil", title: t('buttons.edit') %>&nbsp;
          <%= link_to "", aluno, method: :delete, data: { confirm: t('messages.confirm') }, class: "glyphicon glyphicon-remove", title: t('buttons.destroy') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="panel-footer text-center" style="padding: 0;">
    <%= paginate @alunos %>
  </div>
</div>

<%= link_to t('buttons.new'), new_aluno_path, class: "btn btn-default" %>

app/views/alunos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.including')} #{t('activerecord.models.aluno.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>