config/routes.rb
Rails.application.routes.draw do

  resources :matriculas, except: :show
  resources :cursos, except: :show
  resources :alunos, except: :show

  post 'matriculas/pagamento/:id(.:format)', to: 'pagamento_matricula#edit', as: 'matriculas/pagamento'
  put 'matriculas/cancellation/:id(.:format)', to: 'matriculas#cancellation', as: 'matriculas/cancellation'
  get 'home/index'
  root 'home#index'

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  before_destroy :curso_matriculado?
  has_many :matriculas

  validates_associated :matriculas
  validates_uniqueness_of :nome
  validates_presence_of :nome, :valor_inscricao
  validates_numericality_of :valor_inscricao, { message: I18n.t('messages.numbers_only'), allow_blank: true }
  validates :nome, length: { maximum: 255, message: I18n.t('messages.max_255') }

  private
  def curso_matriculado?
    if Matricula.where("aluno_id = ?", id).count > 0
      return false
    end

    return true
  end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all.page(params[:page]).per(15)
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to cursos_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to cursos_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    if @curso.destroy
      respond_to do |format|
        format.html { redirect_to cursos_path, notice: I18n.t('messages.destroyed') }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to cursos_path, alert: I18n.t('messages.error_destroyed') }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_options_for_select
      @periodo_options_for_select = [[I18n.t('options.morning'), 1], [I18n.t('options.afternoon'), 2], [I18n.t('options.integral'), 3]]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :valor_inscricao, :periodo)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
  def busca_descricao_periodo(periodo)
    case periodo
      when 1 then 'Matutino'
      when 2 then 'Vespertino'
      when 3 then 'Integral'
    end
  end
end

app/views/cursos/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@curso, html: { class: "form-horizontal" }) do |f| %>
      <div class="form-group">
        <%= f.label :nome, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :nome, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :valor_inscricao, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.text_field :valor_inscricao, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :periodo, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.select :periodo, options_for_select(@periodo_options_for_select), {}, { class: 'form-control' } %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
          <%= f.submit t('buttons.save'), class: "btn btn-default" %>
          <%= link_to t('buttons.back'), cursos_path, class: "btn btn-default"%>
        </div>
      </div>

      <% if @curso.errors.any? %>
        <div id="error_explanation" class="alert alert-danger col-xs-offset-1 col-xs-10" role="alert">
          <ul>
          <% @curso.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

    <script type="text/javascript">
      $(".form-group:has(.field_with_errors)").addClass("has-error");
    </script>
  </div>
</div>

app/views/cursos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.editing')} #{t('activerecord.models.curso.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>

app/views/cursos/index.html.erb
<% if notice != nil %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <%= notice %>
  </div>
<% end %>

<% if alert != nil %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
    <%= alert %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.listing')} #{@cursos.model.model_name.human(count: 2)}" %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @cursos.model.human_attribute_name("nome") %></th>
        <th><%= @cursos.model.human_attribute_name("valor_inscricao") %></th>
        <th><%= @cursos.model.human_attribute_name("periodo") %></th>
        <th><%= t("buttons.actions") %></th>
      </tr>
    </thead>

    <tbody>
      <% @cursos.each do |curso| %>
        <tr>
          <td><%= curso.nome %></td>
          <td><%= format("%.2f", curso.valor_inscricao) %></td>
          <td><%= busca_descricao_periodo(curso.periodo) %></td>
          <td><%= link_to "", edit_curso_path(curso), class: "glyphicon glyphicon-pencil", title: t('buttons.edit') %>&nbsp;
          <%= link_to "", curso, method: :delete, data: { confirm: t('messages.confirm') }, class: "glyphicon glyphicon-remove", title: t('buttons.destroy') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="panel-footer text-center" style="padding: 0;">
    <%= paginate @cursos %>
  </div>
</div>

<%= link_to t('buttons.new'), new_curso_path, class: "btn btn-default" %>

app/views/cursos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.including')} #{t('activerecord.models.curso.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>