config/routes.rb
Rails.application.routes.draw do

  resources :matriculas, except: :show
  resources :cursos, except: :show
  resources :alunos, except: :show

  post 'matriculas/pagamento/:id(.:format)', to: 'pagamento_matricula#edit', as: 'matriculas/pagamento'
  put 'matriculas/cancellation/:id(.:format)', to: 'matriculas#cancellation', as: 'matriculas/cancellation'
  get 'home/index'
  root 'home#index'

end

app/models/matricula.rb
class Matricula < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :curso

  validates_presence_of :ano, :aluno_id, :curso_id
  validates_numericality_of :ano, { only_integer: true, message: I18n.t('messages.numbers_only'), allow_blank: true }

  validate :periodo_ano_unico

  private
  def periodo_ano_unico
    periodo = Curso.find(curso_id).periodo
    matricula = Matricula.where("aluno_id = ? AND ano = ?", aluno_id, ano)

    if id != nil
      matricula = matricula.where("matriculas.id <> ?", id)
    end

    matricula = matricula.joins(:curso).where(cursos: { periodo: [periodo, 3] })

    if (matricula.count > 0) || (matricula.count == 0 && periodo == 3)
      errors.add(:aluno_id, " #{I18n.t('messages.enrolled')}")
    end
  end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController
  before_action :set_matricula, only: [:edit, :update, :destroy, :cancellation]
  before_action :set_alunos_options_for_select, :set_cursos_options_for_select, :set_sim_nao_options_for_select, only: [:new, :edit, :update, :create]

  # GET /matriculas
  # GET /matriculas.json
  def index
    if params[:commit].present?
      @matriculas = Matricula.all
      @matriculas = @matriculas.joins(:aluno).where("alunos.nome LIKE '%#{params[:aluno]}%'") if params[:aluno].present?
      @matriculas = @matriculas.joins(:curso).where("cursos.nome LIKE '%#{params[:curso]}%'") if params[:curso].present?
      @matriculas = @matriculas.where("ano = #{params[:ano]}") if params[:ano].present?
      @matriculas = @matriculas.where("pago = 0") if params[:pagamento_pendente].present?
    else
      @matriculas = Matricula.where(ativo: 1)
    end

    @matriculas = @matriculas.page(params[:page]).per(15)
  end

  # GET /matriculas/new
  def new
    @matricula = Matricula.new
  end

  # GET /matriculas/1/edit
  def edit
  end

  def filter

  end

  # POST /matriculas
  # POST /matriculas.json
  def create
    @matricula = Matricula.new(matricula_params)

    respond_to do |format|
      if @matricula.save
        format.html { redirect_to matriculas_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @matricula }
      else
        format.html { render :new }
        format.json { render json: @matricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matriculas/1
  # PATCH/PUT /matriculas/1.json
  def update
    respond_to do |format|
      if @matricula.update(matricula_params)
        format.html { redirect_to matriculas_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @matricula }
      else
        format.html { render :edit }
        format.json { render json: @matricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matriculas/1
  # DELETE /matriculas/1.json
  def destroy
    @matricula.destroy
    respond_to do |format|
      format.html { redirect_to matriculas_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  def cancellation
    @matricula.update(ativo: 0)

    respond_to do |format|
      format.html { redirect_to matriculas_path, notice: I18n.t('messages.canceled') }
      format.json { head :no_content }
    end
  end

  private
    def set_alunos_options_for_select
      @alunos_options_for_select = Aluno.all
    end

    def set_cursos_options_for_select
      @cursos_options_for_select = Curso.all
    end

    def set_sim_nao_options_for_select
      @sim_nao_options_for_select = [[I18n.t('options.no'), 0], [I18n.t('options.yes'), 1]]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_matricula
      @matricula = Matricula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matricula_params
      params.require(:matricula).permit(:aluno_id, :curso_id, :data_matricula, :ano, :ativo, :pago)
    end
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
  def busca_sim_nao(valor)
    case valor
      when 0 then I18n.t('options.no')
      when 1 then I18n.t('options.yes')
    end
  end
end

app/views/matriculas/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@matricula, html: { class: "form-horizontal" }) do |f| %>
      <div class="form-group">
        <%= f.label :aluno_id, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.collection_select(:aluno_id, @alunos_options_for_select, :id, :nome, {}, { class: 'form-control' }) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :curso_id, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.collection_select(:curso_id, @cursos_options_for_select, :id, :nome, {}, { class: 'form-control' }) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :data_matricula, class: "col-xs-2 control-label" %>
        <div class="col-xs-8 date">
          <%= f.date_select :data_matricula, start_year: Date.current.year, end_year: 1900 %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ano, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.number_field :ano, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :pago, class: "col-xs-2 control-label" %>
        <div class="col-xs-8">
          <%= f.select :pago, options_for_select(@sim_nao_options_for_select), {}, { class: 'form-control' } %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
          <%= f.submit t('buttons.save'), class: "btn btn-default" %>
          <%= link_to t('buttons.back'), matriculas_path, class: "btn btn-default"%>
        </div>
      </div>

      <%= f.hidden_field :ativo, value: 1 %>

      <% if @matricula.errors.any? %>
        <div id="error_explanation" class="alert alert-danger col-xs-offset-1 col-xs-10" role="alert">
          <ul>
          <% @matricula.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

    <script type="text/javascript">
      $(".form-group:has(.field_with_errors)").addClass("has-error");
      $(".date > select").addClass("form-control").css("width", "33.33%").css("float", "left");
    </script>
  </div>
</div>

app/views/matriculas/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.editing')} #{t('activerecord.models.matricula.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>

app/views/matriculas/index.html.erb
<% if notice != nil %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
    <%= notice %>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.filters')}" %>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12">
      <%= form_tag(matriculas_path, :method => "get", class: "form-horizontal") do %>
        <div class="form-group">
          <div class="col-xs-3">
            <%= label_tag :aluno, t('activerecord.models.aluno.one'), class: "col-xs-3" %>
            <div class="col-xs-9">
              <%= text_field_tag :aluno, params[:aluno], class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-3">
            <%= label_tag :curso, t('activerecord.models.curso.one'), class: "col-xs-3" %>
            <div class="col-xs-9">
              <%= text_field_tag :curso, params[:curso], class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-2">
            <%= label_tag :ano, t('activerecord.attributes.matricula.ano'), class: "col-xs-1" %>
            <div class="col-xs-8">
              <%= text_field_tag :ano, params[:ano], class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-3">
            <div class="col-xs-1">
              <input type="checkbox" name="pagamento_pendente" <%= params[:pagamento_pendente] != nil ? "checked='checked'" : "" %>>
            </div>
            <%= label_tag :pagamento_pendente, t('buttons.pending_payment'), class: "col-xs-10" %>
          </div>
          <%= submit_tag t('buttons.filter'), class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.listing')} #{@matriculas.model.model_name.human(count: 2)}" %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @matriculas.model.human_attribute_name("aluno") %></th>
        <th><%= @matriculas.model.human_attribute_name("curso") %></th>
        <th><%= @matriculas.model.human_attribute_name("data_matricula") %></th>
        <th><%= @matriculas.model.human_attribute_name("ano") %></th>
        <th><%= @matriculas.model.human_attribute_name("ativo") %></th>
        <th><%= @matriculas.model.human_attribute_name("pago") %></th>
        <th class="text-center"><%= t("buttons.payment") %></th>
        <th class="text-center"><%= t("buttons.cancellation") %></th>
        <th><%= t("buttons.actions") %></th>
      </tr>
    </thead>

    <tbody>
      <% @matriculas.each do |matricula| %>
        <tr>
          <td><%= matricula.aluno.nome %></td>
          <td><%= matricula.curso.nome %></td>
          <td><%= matricula.data_matricula.strftime("%d/%m/%Y") %></td>
          <td><%= matricula.ano %></td>
          <td><%= busca_sim_nao(matricula.ativo) %></td>
          <td><%= busca_sim_nao(matricula.pago) %></td>
          <td class="text-center">
            <% if matricula.pago == 1 %>
              -
            <% else %>
              <%= link_to "", matriculas_pagamento_path(matricula), method: :post, class: "glyphicon glyphicon-usd", title: t('buttons.pay') %>
            <% end %>
          </td>
          <td class="text-center">
            <% if matricula.ativo == 0 %>
              -
            <% else %>
              <%= link_to "", matriculas_cancellation_path(matricula), method: :put, data: { confirm: t('messages.cancel_matricula') }, class: "glyphicon glyphicon-ban-circle", title: t('buttons.cancel') %>
            <% end %>
          </td>
          <td><%= link_to "", edit_matricula_path(matricula), class: "glyphicon glyphicon-pencil", title: t('buttons.edit') %>&nbsp;
          <%= link_to "", matricula, method: :delete, data: { confirm: t('messages.confirm') }, class: "glyphicon glyphicon-remove", title: t('buttons.destroy') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="panel-footer text-center" style="padding: 0;">
    <%= paginate @matriculas %>
  </div>
</div>

<%= link_to t('buttons.new'), new_matricula_path, class: "btn btn-default" %>

app/views/matriculas/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "#{t('messages.including')} #{t('activerecord.models.matricula.one')}" %>
  </div>
  <br>
  <%= render 'form' %>
</div>