config/routes.rb
Rails.application.routes.draw do

  resources :matriculas, except: :show
  resources :cursos, except: :show
  resources :alunos, except: :show

  post 'matriculas/pagamento/:id(.:format)', to: 'pagamento_matricula#edit', as: 'matriculas/pagamento'
  put 'matriculas/cancellation/:id(.:format)', to: 'matriculas#cancellation', as: 'matriculas/cancellation'
  get 'home/index'
  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('title') %></title>
  <link rel="shortcut icon" href="<%= image_url('icone.ico') %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% url = request.original_fullpath %>

  <div class="container">
    <div class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li class="<%= url == '/' ? 'active' : '' %>"><%= link_to t('home'), root_path %></li>
          <li class="<%= url.include?('alunos') ? 'active' : '' %>"><%= link_to t('activerecord.models.aluno.other'), alunos_path %></li>
          <li class="<%= url.include?('cursos') ? 'active' : '' %>"><%= link_to t('activerecord.models.curso.other'), cursos_path %></li>
          <li class="<%= url.include?('matriculas') ? 'active' : '' %>"><%= link_to t('activerecord.models.matricula.other'), matriculas_path %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <div class="modal fade" id="modal_info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"><%= t('information') %></h4>
        </div>
        <div id="modal_info_body" class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
        </div>
      </div>
    </div>
  </div>
</body>
</html>